Private Events
yahir91/private-events pull request #1
Opened 2020-08-20 21:53 UTC by yahir91

In this project, we created a webpage that users can create events and attend to other events.

We had to use associations to link the events with the users.
We had to use scopes to select previews and upcoming events.

2020-08-21 00:03 UTC, rOluochKe requested changes
Hello @yahir91 and @maosan132 
### You have done well so far :clap: However, you have a few issues to fix before the app can be approved.
- [ ] Remove the comments in your codebase
- [ ] I was unable to create events, I get an error. Refer to the image below
![contr](https://user-images.githubusercontent.com/8114528/90837293-4ad11680-e35a-11ea-97b7-89b360307039.png)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

2020-08-21 06:16 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @yahir91 and @maosan132, great project. You have done a great job :+1: However, we need to address the comment below before we can approve the project :slightly_smiling_face: 

- Ass pointed out by the previous TSE, I could also not create an event. Below is the screenshot of the error
![er](https://user-images.githubusercontent.com/46388113/90858031-dc4d8200-e374-11ea-8675-1a9536b88450.png)
- We are also missing test for this project, let us write `unit` and `integration` test for the app
- Our README is also missing an important section, which is the `setup` section, where we describe how to clone and run the project successfully

Kindly implement these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-08-21 21:03 UTC, maosan132 commented
Thanks. We made the changes requested, in #2 and #3 points, As for the #1 point, please proceed as readme says.

2020-08-21 22:47 UTC, maelfosso reviewed
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes.
However, there are still some issues

1. After sign up, I got this
![Screenshot at 2020-08-21 23:38:11](https://user-images.githubusercontent.com/8848104/90940683-8675ea00-e407-11ea-886d-1442be17b624.png)
The navbar, as you can notice, has still the link for **Sign Up** and **Sign In**. Why these links ?

Those links disappear only after a successful Sign In. Please, fix your navigation diagram

2. I got this error when creating an event
![Screenshot at 2020-08-21 23:41:45](https://user-images.githubusercontent.com/8848104/90940782-ea001780-e407-11ea-96e2-59490a006342.png)

3. As requested [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) and  [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png], please, add integration tests. For unit test, use **shoulda-matchers** gems

5. Please, enable Linter's or Github Actions in this repository

Once apply the suggested changes, please, submit a new code reviiew request
Thanks

Mael FOSSO

2020-08-26 17:01 UTC, yahir91 commented
Thanks for your review.
The first issue is solved, now when you create a user it automatically login.
For the second issue run `rails db:reset` first in your command line that will solve that problem, just as the readme says.
The tests were added and the linters too.

2020-08-26 19:03 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, great job fixing all the comments made by the previous TSE's :+1: Congratulations, our project now meets all the minimum requirements :smile: 

Good luck with your next projects :100: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-08-26 19:03 UTC, addod19 commented on config/routes.rb
> +  resources :sessions
[OPTIONAL]
Let us use specific routes for our App, for example `resources :session, only: [:create, :destroy]`

2020-08-26 19:03 UTC, addod19 commented on app/models/event.rb
> +  # validates :date, presence: true
[OPTIONAL]
Kindly remove the comment

2020-08-26 19:03 UTC, addod19 commented on spec/models/event_spec.rb
> +  # it { should validate_presence_of(:date) }
[OPTIONAL]
Kindly remove the commented code

2020-09-16 22:07 UTC, merged